name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up gcloud CLI
      - name: Configure gcloud
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REPO }}:${{ github.sha }} .
          docker tag ${{ secrets.ARTIFACT_REPO }}:${{ github.sha }} ${{ secrets.ARTIFACT_REPO }}:latest

      # Push Docker Image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ARTIFACT_REPO }}:${{ github.sha }}
          docker push ${{ secrets.ARTIFACT_REPO }}:latest

      # Get GKE Credentials
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      # Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl set image deployment/my-app my-app=${{ secrets.ARTIFACT_REPO }}:${{ github.sha }}
